- name: Checkout
uses: actions/checkout@v3
  
- name: Package VS Code Extension
id: package
# You may pin to the exact commit or the version.
# uses: nhedger/package-vscode-extension@102a29378b80b78b38adfa820c41387f406aa4f3
uses: nhedger/package-vscode-extension@v1

- name: Publish VS Code extension artifact
uses: actions/upload-artifact@v3
with:
    name: vscode-time-keeper
    path: ${{ steps.package.outputs.packagePath }}
