name: Publish
on:
  push:
    branches:
      - master
jobs:
  publish-vsix:
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Package VS Code Extension
        id: package
        uses: nhedger/package-vscode-extension@v1
      - name: Publish VS Code extension artifact
        uses: actions/upload-artifact@v3
        with:
          name: vscode-time-keeper
          path: '${{ steps.package.outputs.packagePath }}'
